spring.application.name=demo
spring.threads.virtual.enabled=true

# Qdrant
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=api
spring.ai.vectorstore.qdrant.initialize-schema=true

# Ollama Embeddings
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text

# OpenRouter Chat
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.model=openai/gpt-oss-120b
spring.ai.openai.chat.max-tokens=2000

logging.level.org.springframework.ai=DEBUG
logging.level.com.openai=DEBUG